export { default as Header } from './header/Header'
export { default as WhatGPT3 } from './whatgpt3/WhatGPT3'
export { default as Brand } from './brand/Brand'
export { default as Possibility } from './possibility/Possibility'
export { default as CTA } from './cta/CTA'
export { default as Footer } from './footer/Footer'
export { default as Blog } from './blog/Blog'
export { default as Features } from './features/Features'